### ISSUE TITLE
Not having much luck with v1.0beta pre-release

### ISSUE THREAD

**Issue by perryk** [scriptingosx/quickpkg#5]
Hi,

I tried using the latest v1.0beta pre-release when I was using 12.2 with both MacAdmins python installed along with the system python2 and found only 1 or 2 times that the new beta version worked. The previous version of quickpkg was always working for the same commands at that time.

I've now updated to 12.3beta with the system python2 removed and still having problems. I've in the meantime upgraded to MacAdmins python version 3.9.10 however the same issue remains.

I'm not sure if this gives much information however it is the output from a simple ./quickpkg ~/Downloads/something.dmg command.

```Traceback (most recent call last):
  File "/Users/uqpkollm/Desktop/quickpkg-1.0beta/./quickpkg", line 277, in <module>
    dmgvolumepaths = attachdmg(item_path)
  File "/Users/uqpkollm/Desktop/quickpkg-1.0beta/./quickpkg", line 88, in attachdmg
    (theplist, alltext) = getFirstPlist(info_result["stdout"])
  File "/Users/uqpkollm/Desktop/quickpkg-1.0beta/./quickpkg", line 52, in getFirstPlist
    plist_start_index = textString.find(plist_header)
TypeError: argument should be integer or bytes-like object, not 'str'
```

Happy to help with any testing/troubleshooting if I can be of assistance.

Cheers.

**Comment by scriptingosx** [comment]
This should be addressed in eaa7d28. Can you test?

**Comment by perryk** [comment]
Thanks, things are certainly better. Apologies I thought I had seen it fail with app bundles but perhaps I more commonly create .pkgs from .dmgs rather than trying to package up something I already have installed.

I've tried with 4 random .dmgs from my Downloads and 3 worked without any trouble.  Just one failed, which perhaps is something related to only that file.  I obtained flameshot.dmg from here: https://github.com/flameshot-org/flameshot/releases/tag/v11.0.0

Then when I run quickpkg I receive the following error:

```╭─ ~/Desktop/quickpkg-main                                                                                                                                                                                                                                                                            ✔  09:35:57 pm ─╮
╰─ ./quickpkg ~/Downloads/flameshot.dmg                                                                                                                                                                                                                                                                                  ─╯
Error Code: 1
b'pkgbuild: error: (null)'
```

**Comment by scriptingosx** [comment]
ugh, that app has an _empty_ CFBundleShortVersionString in its Info.plist. quickpkg could handle a _missing_ short version string, but it chokes on the empty one...

**Comment by scriptingosx** [comment]
Not a hard fix, though: 924174b

**Comment by scriptingosx** [comment]
I'll close this for now, you can open other issues if you find more, thanks!

**Comment by perryk** [comment]
Tested and all working fine with flameshot. Thanks again :)
