### ISSUE TITLE
MacAdmins "Managed Python" issue

### ISSUE THREAD

**Issue by andreped** [scriptingosx/quickpkg#7]
I have been using quickpkg in a project. Everything has worked as expected. However, I got an issue today when I returned to the project and needed to run some CI tests.

```
> git clone https://github.com/scriptingosx/quickpkg.git
> quickpkg/quickpkg dist/someApp.app --output someApp-1.0.0-macOS.pkg
```

Resulted in:
```
Cloning into 'quickpkg'...
/Users/runner/work/_temp/5fb59a5c-97d8-4069-bf10-0169e67a8e01.sh: quickpkg/quickpkg: /usr/local/bin/managed_python3: bad interpreter: No such file or directory
Error: Process completed with exit code 126.
```

This was tested on a hosted runner (GitHub Actions), on macos 10.15, using python 3.7.

---
From our discussion [here](https://github.com/scriptingosx/quickpkg/commit/2927f67a67deba7a25075a8972671e4acab0b191), it seems like I am using the wrong python version when using quickpkg. I had not seen the updated requirements in the [README](https://github.com/scriptingosx/quickpkg#dependencies).

Therefore, I should use the MacAdmins "Managed Python" version instead. However, I am not familiar with it. I am currently using GitHub Actions, and I am unable to find this python version, at least as an action. Have you tried or found it?

In advance, thanks!

**Comment by scriptingosx** [comment]
The [ReadMe](https://github.com/scriptingosx/quickpkg#dependencies) contains a link to the project. I will repeat it here in case you have trouble following the link in the ReadMe:

[MacAdmins Managed Python](https://github.com/macadmins/python)

**Comment by andreped** [comment]
@scriptingosx My bad! Was not aware of how this change would affect my project. In the end, I just reverted back to using an older release of quickpkg. Will handle the MacAdmins Managed Python issue down the line, but then quickpkg is not the issue, but rather which python version I use.

Happy with the quickpkg tool. Been a great solution for my projects. Thanks! :]
